name: Build x64 macOS Installer 
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      # Import and set up the signing certificate
      - name: Import Signing Certificate
        env:
          CERTIFICATE_B64: ${{ secrets.SIGNING_CERT }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          KEYCHAIN_PATH: "${{ runner.temp }}/app-signing.keychain-db"
          KEYCHAIN_PASSWORD: "temporary-password"
        run: |
          # Create the keychain
          security create-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
          security set-keychain-settings -lut 21600 "${KEYCHAIN_PATH}"
          security unlock-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
          
          # Add keychain to search list
          security list-keychains -d user -s "${KEYCHAIN_PATH}" $(security list-keychains -d user | sed s/\"//g)
          
          # Decode and import certificate
          echo "${CERTIFICATE_B64}" | base64 --decode > "${{ runner.temp }}/certificate.p12"
          security import "${{ runner.temp }}/certificate.p12" -P "${CERTIFICATE_PASSWORD}" -A -t cert -f pkcs12 -k "${KEYCHAIN_PATH}"
          
          # Allow codesign to access the certificate without UI interaction
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
          
          # Clean up the temporary certificate file
          rm "${{ runner.temp }}/certificate.p12"
          
          # Print available identities for debugging
          echo "Available identities in keychain:"
          security find-identity -v "${KEYCHAIN_PATH}"
          
          # Make sure the keychain is default and unlocked
          security default-keychain -s "${KEYCHAIN_PATH}"
          security unlock-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
       
      - name: Install dependencies
        run: npm install
        working-directory: genaiservices-electron-app
        
      - name: Build the Electron app
        run: npm run build-mac
        working-directory: genaiservices-electron-app
        
      - name: Sign DMG
        env:
          KEYCHAIN_PATH: "${{ runner.temp }}/app-signing.keychain-db"
          KEYCHAIN_PASSWORD: "temporary-password"
        run: |
          # Unlock the keychain again before signing
          security unlock-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
          
          # List available identities again to confirm
          echo "Available identities before signing:"
          security find-identity -v "${KEYCHAIN_PATH}"
          
          # Use the full identity string from the output
          IDENTITY=$(security find-identity -v "${KEYCHAIN_PATH}" | grep "Developer ID Application" | head -1 | awk '{print $2}')
          echo "Using identity: ${IDENTITY}"
          
          # Find the DMG file(s)
          DMG_FILES=$(find genaiservices-electron-app/dist/prod -name "*.dmg" -type f)
          
          # Sign each DMG file
          for DMG_FILE in ${DMG_FILES}; do
            echo "Signing DMG: ${DMG_FILE}"
            codesign --force --sign "${IDENTITY}" --keychain "${KEYCHAIN_PATH}" --timestamp --verbose "${DMG_FILE}"
            
            # Verify the signature
            echo "Verifying signature for: ${DMG_FILE}"
            codesign -vvv --deep --strict "${DMG_FILE}"
          done
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-prod-build-x64
          path: genaiservices-electron-app/dist/prod
